apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  progressDeadlineSeconds: 15
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
  containers:
  - name: helloworld
    image: docker.io/crccheck/hello-world:latest
    imagePullPolicy: IfNotPresent
