apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-{{ .Values.environment }}
  labels:
    app: helloworld
spec:
  progressDeadlineSeconds: 15
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: crccheck/hello-world:latest
        imagePullPolicy: IfNotPresent